In [34]:
import pandas as pd
import polars as pl
import polars.selectors as cs
import numpy as np
import plotnine as pn
import matplotlib.pyplot as plt
from mizani.formatters import comma_format, custom_format, currency_format, percent_format
from IPython.display import clear_output, display
import os
import glob
from tqdm.notebook import tqdm
import itertools
import yaml
import matplotlib.font_manager as fm
import matplotlib as mpl
from matplotlib import rc
import time

# OpenMeteo API
import openmeteo_requests
import requests_cache
from retry_requests import retry

rc('text', usetex=False)

jama_colour = [
    "#374e55",
    "#df8f44",
    "#00a1d5",
    "#b24745",
    "#79af97",
]

pd.set_option("display.max.columns", 500)
pd.set_option("display.max.columns", 500)


theme_academic = pn.theme(
    text=pn.element_text(family="Latin Modern Roman"),
    plot_title=pn.element_text(weight="bold", size=14, ha="center"),
    legend_text=pn.element_text(size=9),  # Smaller font for legend items
    panel_background=pn.element_rect(fill="white"),  # Clean white background
    panel_border=pn.element_rect(color="grey", size=0.5),
    axis_ticks=pn.element_line(color="grey"),
    panel_grid_major=pn.element_line(color="grey", size=0.1),
    panel_grid_minor=pn.element_line(color="grey", size=0.1),
    legend_background=pn.element_rect(fill="white", color=None),
    legend_key=pn.element_rect(fill="white", color=None),
    plot_margin=0.02,
    figure_size=(6, 4),  # Set default figure size (width, height in inches)
)

%matplotlib inline

# Swissgrid Energiestatistik

In [2]:
energieuebersicht_paths = [
    path for path in os.listdir("../0_data/raw/") if "EnergieUebersicht" in path
]

In [3]:
load_dfs = []

for path in tqdm(energieuebersicht_paths):
    df_tmp = (
        pl.read_excel(
            source=f"../0_data/raw/{path}",
            sheet_name="Zeitreihen0h15",
        )
        .select(pl.nth(0), pl.nth(1))
        .tail(-1)
    )

    df_tmp.columns = ["datetime", "kWh"]

    df_tmp = df_tmp.with_columns(
        datetime=(
            pl.col("datetime").str.to_datetime() - pd.Timedelta(15, unit="minutes")
        ),
        kWh=pl.col("kWh").cast(pl.Float64),
    ).sort("datetime")

    load_dfs.append(df_tmp)

  0%|          | 0/16 [00:00<?, ?it/s]

In [4]:
load = pl.concat(load_dfs, how="vertical").sort("datetime")
load.head()

shape: (5, 2)
┌─────────────────────┬──────────┐
│ datetime            ┆ kWh      │
│ ---                 ┆ ---      │
│ datetime[μs]        ┆ f64      │
╞═════════════════════╪══════════╡
│ 2009-01-01 00:00:00 ┆ 1.8300e6 │
│ 2009-01-01 00:15:00 ┆ 1.7152e6 │
│ 2009-01-01 00:30:00 ┆ 1.7326e6 │
│ 2009-01-01 00:45:00 ┆ 1.7067e6 │
│ 2009-01-01 01:00:00 ┆ 1.7224e6 │
└─────────────────────┴──────────┘

In [5]:
load.to_pandas().to_csv("../0_data/preprocessed/load.csv", index=False)

# OpenMeteo API

[API Link](https://open-meteo.com/en/docs/historical-weather-api)

In [41]:
cities = pd.DataFrame(
    {
        "name": [
            "Zurich",
            "Geneva",
            "Basel",
            "Bern",
            "St. Gallen",
            "Lugano",
            "Sion",
        ],
        "latitude": [
            47.3769,
            46.2044,
            47.5596,
            46.948,
            47.4245,
            46.0037,
            46.2331,
        ],
        "longitude": [
            8.5417,
            6.1432,
            7.5886,
            7.4474,
            9.3767,
            8.9511,
            7.3606,
        ],
    }
)

cities

         name  latitude  longitude
0  St. Gallen   47.4245     9.3767
1      Lugano   46.0037     8.9511
2        Sion   46.2331     7.3606

In [42]:
# Setup the Open-Meteo API client with cache and retry on error
cache_session = requests_cache.CachedSession(".cache", expire_after=-1)
retry_session = retry(cache_session, retries=5, backoff_factor=0.2)
openmeteo = openmeteo_requests.Client(session=retry_session)

# Make sure all required weather variables are listed here
# The order of variables in hourly or daily is important to assign them correctly below
url = "https://archive-api.open-meteo.com/v1/archive"

In [43]:
for idx, city in cities.iterrows():
    params = {
        "latitude": city["latitude"],
        "longitude": city["longitude"],
        "start_date": "2009-01-01",
        "end_date": "2024-10-10",
        "hourly": [
            "temperature_2m",
            "relative_humidity_2m",
            "dew_point_2m",
            "apparent_temperature",
            "precipitation",
            "rain",
            "snowfall",
            "snow_depth",
            "cloud_cover",
            "wind_speed_10m",
            "wind_speed_100m",
            "wind_direction_10m",
            "wind_direction_100m",
            "wind_gusts_10m",
            "soil_temperature_0_to_7cm",
            "soil_temperature_7_to_28cm",
            "soil_temperature_28_to_100cm",
            "soil_temperature_100_to_255cm",
            "soil_moisture_0_to_7cm",
            "soil_moisture_7_to_28cm",
            "soil_moisture_28_to_100cm",
            "soil_moisture_100_to_255cm",
            "shortwave_radiation",
        ],
        "timezone": "Europe/Berlin",
    }
    responses = openmeteo.weather_api(url, params=params)

    # Process first location. Add a for-loop for multiple locations or weather models
    response = responses[0]
    print(f"Coordinates {response.Latitude()}°N {response.Longitude()}°E")
    print(f"Elevation {response.Elevation()} m asl")
    print(f"Timezone {response.Timezone()} {response.TimezoneAbbreviation()}")
    print(f"Timezone difference to GMT+0 {response.UtcOffsetSeconds()} s")

    # Process hourly data. The order of variables needs to be the same as requested.
    hourly = response.Hourly()
    hourly_temperature_2m = hourly.Variables(0).ValuesAsNumpy()
    hourly_relative_humidity_2m = hourly.Variables(1).ValuesAsNumpy()
    hourly_dew_point_2m = hourly.Variables(2).ValuesAsNumpy()
    hourly_apparent_temperature = hourly.Variables(3).ValuesAsNumpy()
    hourly_precipitation = hourly.Variables(4).ValuesAsNumpy()
    hourly_rain = hourly.Variables(5).ValuesAsNumpy()
    hourly_snowfall = hourly.Variables(6).ValuesAsNumpy()
    hourly_snow_depth = hourly.Variables(7).ValuesAsNumpy()
    hourly_cloud_cover = hourly.Variables(8).ValuesAsNumpy()
    hourly_wind_speed_10m = hourly.Variables(9).ValuesAsNumpy()
    hourly_wind_speed_100m = hourly.Variables(10).ValuesAsNumpy()
    hourly_wind_direction_10m = hourly.Variables(11).ValuesAsNumpy()
    hourly_wind_direction_100m = hourly.Variables(12).ValuesAsNumpy()
    hourly_wind_gusts_10m = hourly.Variables(13).ValuesAsNumpy()
    hourly_soil_temperature_0_to_7cm = hourly.Variables(14).ValuesAsNumpy()
    hourly_soil_temperature_7_to_28cm = hourly.Variables(15).ValuesAsNumpy()
    hourly_soil_temperature_28_to_100cm = hourly.Variables(16).ValuesAsNumpy()
    hourly_soil_temperature_100_to_255cm = hourly.Variables(17).ValuesAsNumpy()
    hourly_soil_moisture_0_to_7cm = hourly.Variables(18).ValuesAsNumpy()
    hourly_soil_moisture_7_to_28cm = hourly.Variables(19).ValuesAsNumpy()
    hourly_soil_moisture_28_to_100cm = hourly.Variables(20).ValuesAsNumpy()
    hourly_soil_moisture_100_to_255cm = hourly.Variables(21).ValuesAsNumpy()
    hourly_shortwave_radiation = hourly.Variables(22).ValuesAsNumpy()

    hourly_data = {
        "date": pd.date_range(
            start=pd.to_datetime(hourly.Time(), unit="s", utc=True),
            end=pd.to_datetime(hourly.TimeEnd(), unit="s", utc=True),
            freq=pd.Timedelta(seconds=hourly.Interval()),
            inclusive="left",
        )
    }
    hourly_data["temperature_2m"] = hourly_temperature_2m
    hourly_data["relative_humidity_2m"] = hourly_relative_humidity_2m
    hourly_data["dew_point_2m"] = hourly_dew_point_2m
    hourly_data["apparent_temperature"] = hourly_apparent_temperature
    hourly_data["precipitation"] = hourly_precipitation
    hourly_data["rain"] = hourly_rain
    hourly_data["snowfall"] = hourly_snowfall
    hourly_data["snow_depth"] = hourly_snow_depth
    hourly_data["cloud_cover"] = hourly_cloud_cover
    hourly_data["wind_speed_10m"] = hourly_wind_speed_10m
    hourly_data["wind_speed_100m"] = hourly_wind_speed_100m
    hourly_data["wind_direction_10m"] = hourly_wind_direction_10m
    hourly_data["wind_direction_100m"] = hourly_wind_direction_100m
    hourly_data["wind_gusts_10m"] = hourly_wind_gusts_10m
    hourly_data["soil_temperature_0_to_7cm"] = hourly_soil_temperature_0_to_7cm
    hourly_data["soil_temperature_7_to_28cm"] = hourly_soil_temperature_7_to_28cm
    hourly_data["soil_temperature_28_to_100cm"] = hourly_soil_temperature_28_to_100cm
    hourly_data["soil_temperature_100_to_255cm"] = hourly_soil_temperature_100_to_255cm
    hourly_data["soil_moisture_0_to_7cm"] = hourly_soil_moisture_0_to_7cm
    hourly_data["soil_moisture_7_to_28cm"] = hourly_soil_moisture_7_to_28cm
    hourly_data["soil_moisture_28_to_100cm"] = hourly_soil_moisture_28_to_100cm
    hourly_data["soil_moisture_100_to_255cm"] = hourly_soil_moisture_100_to_255cm
    hourly_data["shortwave_radiation"] = hourly_shortwave_radiation

    hourly_dataframe = pd.DataFrame(data=hourly_data)
    hourly_dataframe.to_csv(
        f"../0_data/raw/weather_data_{city['name']}.csv", index=False
    )

    print(f"{city['name']} done... sleeping to prevent timeout")
    time.sleep(90)

Coordinates 47.41651916503906°N 9.442623138427734°E
Elevation 680.0 m asl
Timezone b'Europe/Berlin' b'CEST'
Timezone difference to GMT+0 7200 s
St. Gallen done... sleeping to prevent timeout
Coordinates 46.01054382324219°N 8.85714340209961°E
Elevation 286.0 m asl
Timezone b'Europe/Berlin' b'CEST'
Timezone difference to GMT+0 7200 s
Lugano done... sleeping to prevent timeout
Coordinates 46.221439361572266°N 7.177033424377441°E
Elevation 526.0 m asl
Timezone b'Europe/Berlin' b'CEST'
Timezone difference to GMT+0 7200 s
Sion done... sleeping to prevent timeout

KeyboardInterrupt: